### ISSUE TITLE
Features which are below the Min_Clust_Threshold

### ISSUE THREAD

**Issue by ogandril** [aradley/FFAVES#28]
When running ffaves.FFAVES or ffaves.ESFW on my dataset, I get the following warning:
Ignoring xxx features which are below the Min_Clust_Threshold
The xxx number may be different when running ffaves.FFAVES or ffaves.ESFW on the same dataset
Any clarification regarding why those features are ignored would be extremely helpfull.

**Comment by aradley** [comment]
Hi,

Sorry for the slow response. I need to link my Github account to my new email address so I get notifications for this sort of thing.

Min_Clust_Threshold is a basic threshold where if a gene has less minority states than Min_Clust_Threshold (default = 20), it is ignored from the analysis due to low predictive power. We give some initial empirical evidence for why we use a default of 20 in our paper. For more detail, please see the supplementals in our paper, in particular, SI 4.

The reason the "xxx" number of ignored features changes between FFAVES and ESFW is because running FFAVES is an attempt to repair spurious minority/majority states in the data. As such, the number of minority states for genes can change, and hence they go above or below Min_Clust_Threshold.

**Comment by ogandril** [comment]
> Le 10 janv. 2023 à 11:13, aradley ***@***.***> a écrit :
> Hi,
> 
> Sorry for the slow response.
> 
Hey, that was fast!
> I need to link my Github account to my new email address so I get notifications for this sort of thing.
> 
> Min_Clust_Threshold is a basic threshold where if a gene has less minority states than Min_Clust_Threshold (default = 20), it is ignored from the analysis due to low predictive power. We give some initial empirical evidence for why we use a default of 20 in our paper. For more detail, please see the supplementals in our paper, in particular, SI 4.
> 
OK, I’ll check that.
> The reason the "xxx" number of ignored features changes between FFAVES and ESFW is because running FFAVES is an attempt to repair spurious minority/majority states in the data. As such, the number of minority states for genes can change, and hence they go above or below Min_Clust_Threshold
> 
OK, thank’s for this information!!! Is there anyway we could detect that before launching FFAVES? Like subselect beforehand a subset of potentially informative genes?

Best

Olivier

**Comment by aradley** [comment]
> OK, thank’s for this information!!! Is there anyway we could detect that before launching FFAVES? Like subselect beforehand a subset of potentially informative genes? Best Olivier

In theory you could pre-filter. I advise against it. The primary purpose of FFAVES/ESFW is to perform unsupervised feature selection of highly informative genes, so to remove genes at the start slightly defeats the point. Having said that, I obviously haven't considered all pre-filtering methods or parameters. If you are confident in a method to pre-filter for you, then by all means try it out and then use FFAVES/ESFW to further prune the gene set.

Are you thinking of doing this to reduce run time? I'm currently working on a significantly faster version, but as I'm between positions, I'm afraid it won't be available for quite some time.

**Comment by ogandril** [comment]
> In theory you could pre-filter. I advise against it. The primary purpose of FFAVES/ESFW is to perform unsupervised feature selection of highly informative genes, so to remove genes at the start slightly defeats the point.
:-)
Makes sense
> Having said that, I obviously haven't considered all pre-filtering methods or parameters. If you are confident in a method to pre-filter for you, then by all means try it out and then use FFAVES/ESFW to further prune the gene set.
That’s the thing. I would like to prune with something that would be « in line » with FFAVES. 
> Are you thinking of doing this to reduce run time?
> 
Yes! When I try on my full dataset (24673 genes x 14371 cells) it takes forever. I mean I had to kill a run that lasted over the week end...
> I'm currently working on a significantly faster version, but as I'm between positions, I'm afraid it won't be available for quite some time.
> 
If (and when) you get a faster version working, let me know. I might still be interested in testing this feature selection method

Best

Olivier

**Comment by aradley** [comment]
> Are you thinking of doing this to reduce run time?
> Yes! When I try on my full dataset (24673 genes x 14371 cells) it takes forever. I mean I had to kill a run that lasted over the week end...

FFAVES/ESFW parallelise well. If you can get around 32 cores on a HPC a dataset like that should like less than 24 hours. That's just an estimate though, and I know not everyone has access to that sort of compute.

**Comment by ogandril** [comment]
> Le 10 janv. 2023 à 12:01, aradley ***@***.***> a écrit :
> Are you thinking of doing this to reduce run time?
> Yes! When I try on my full dataset (24673 genes x 14371 cells) it takes forever. I mean I had to kill a run that lasted over the week end...
> 
> FFAVES/ESFW parallelise well. If you can get around 32 cores on a HPC a dataset like that should like less than 24 hours. That's just an estimate though, and I know not everyone has access to that sort of compute.
> 
Well I do have access to HPC computation. 
Any specific instruction to run FFAVES/ESFW in a parallel mode?
Or is this adjusting by default to the available amount of cores?

Olivier

**Comment by aradley** [comment]
If you just run the code within your HPC, FFAVES/ESFW will automatically detect the available cores and use the number of available cores, minus 1. Or, you can manually set the number of cores with the "Use_Cores" variable.

Essentially it's default is parallel mode, but it will only ever use the number of cores on the device, minus 1, so not to take up all the compute power on a personal desktop.

**Comment by ogandril** [comment]
Perfect, thank’s!!

Olivier
